export const PLAYLIST_SLICE = '5' // playlist分组
export const PLAYLIST_DEFAULT_BUTTON = '华语'
export const PLAYLIST_DEFAULT_VISIBLE = false
export const PLAYLIST_DEFAULT_HASHIGHINFO = true
export const PLAYLIST_QUERYINFO_ORDER = 'hot'
export const PLAYLIST_QUERYINFO_LIMIT = '50'
export const PLAYLIST_QUERYINFO_OFFSET = '50'
export const TOPLIST_SLICE = '4' // toplist分组
export const ARTIST_QUERYINFO_LIMIT = 30
export const QUERYINFO_TYPE = -1
export const QUERYINFO_AREA = -1
export const QUERYINFO_INITIAL = '-1'
export const NEWALBUM_QUERYINFO_LIMIT = 30
export const NEWALBUM_QUERYINFO_OFFSET = 0
export const NEWALBUM_QUERYINFO_AREA = 'ALL'
export const NEWALBUM_QUERYINFO_TYPE = 'new'
export const NEWALBUM_QUERYINFO_MONTH = ''
export const NEWALBUM_QUERYINFO_YEAR = ''
